apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-app
  labels:
    app: react-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend-app
  template:
    metadata:
      labels:
        app: react-frontend-app
    spec:
      containers:
      - name: react-frontend-app
        image: react-frontend-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
